Models/Engineer.cs
using System.Collections.Generic;


namespace Factory.Models
{
    public class Engineer
 {
   public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int EngineerId { get; set; }
    public string Name { get; set; }
    public List<Machine> Machines { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
    }

Controllers/EngineerController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db =db;
    }
    

    public ActionResult Index()
    {
      IEnumerable<Engineer> sortedEngineers = _db.Engineers.OrderBy(engineer => engineer.Name);
      return View(sortedEngineers.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      if (MachineId !=0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

   public ActionResult Details(int id)
{
  var thisEngineer = _db.Engineers
                          .Include(engineer => engineer.JoinEntities)
                          .ThenInclude(join => join.Machine)
                          .FirstOrDefault(engineer => engineer.EngineerId == id);
  return View(thisEngineer);
}


    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]

    public ActionResult Edit(Engineer engineer)
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]

    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        if (_db.EngineerMachines.Any(join => join.MachineId == MachineId && join.EngineerId == engineer.EngineerId) == false)
          _db.EngineerMachines.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]

    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.EngineerId });
    }

  }
}

Controllers/MachineController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      IEnumerable<Machine> sortedMachines = _db.Machines.OrderBy(machine => machine.MachineName);
      return View(sortedMachines.ToList());
    }

    public ActionResult Create()
    {
        ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
    return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine, int EngineerId)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      if (EngineerId !=0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  public ActionResult Details(int id)
{
    var thisMachine = _db.Machines
        .Include(machine => machine.JoinEntities)
            .ThenInclude(join => join.Engineer) // Use ThenInclude to include the Engineer entities
        .FirstOrDefault(machine => machine.MachineId == id);

    return View(thisMachine);
}


    public ActionResult Edit(int id)
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit (Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = machine.MachineId });
    }

     public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }
    
    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }
    

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]

    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]

    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.MachineId });
    }

  }
}

Views/Engineers/AddMachine.cshtml
@{
  Layout ="_Layout";
}
@model Factory.Models.Engineer;
<div class="headder">
  <div class="jumbotron text-center">
    <h1>Factory Control</h1>
    <h2>Machines</h2>
  </div>
  <nav class="navbar sticky-top navbar-expand-sm">
    <div class="container">
      <p class="btn">@Html.ActionLink("Add Machine", "Create", "Machines")</p>
      <p class="btn">@Html.ActionLink("View Engineers", "Index", "Engineers")</p>
      <p class="btn">@Html.ActionLink("Home", "Index", "Home")</p>
    </div>
  </nav>
</div>
<br />
<div class="container">
    @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.EngineerId)
    
    @Html.Label("Add new machine assignment  ")
    @Html.DropDownList("MachineId")
    <br/>
    <button type="Save">Add Machine Assignment</button>
  }
</div>

Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>add a new engineer</h4>

<hr />

@using (Html.BeginForm())
{
  @Html.Label("Name")
  @Html.TextBoxFor(model => model.Name, new { @class = "form-control", required = "required"})

 
  <br>
  @Html.Label("Qualified Machines")
  @Html.DropDownList("MachineId", null, string.Empty)

  <br>
  <br>
  <input type="submit" value="Complete" class="btn btn-default" required="true" />
}

<br>
<p>@Html.ActionLink("back to employee directory", "Index")</p>

Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>are you sure you want to delete this engineer from the employee directory?</h2>

@Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

<br>

@Html.ActionLink("back to employee directory", "Index")

Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>employee details</h2>

<hr />

<h3>@Html.DisplayFor(model => model.Name)</h3>


@if(@Model.JoinEntities.Count == 0)
{
  <p>this engineer does not have any machines assigned to them</p>
}
else
{
  <h4>machines this engineer is qualified to repair:</h4>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Machine.MachineName </li> 
      @using (Html.BeginForm("DeleteMachine", "Engineers"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="remove" />
      }
    }
  </ul>
}

<ul class="menu-links">
  <li>@Html.ActionLink("edit engineer", "Edit", new { id = Model.EngineerId })</li>
  <li>@Html.ActionLink("delete engineer", "Delete", new { id = Model.EngineerId })</li>
  <li>@Html.ActionLink("assign to a machine", "AddMachine", new {id = Model.EngineerId })</li>
  <li>@Html.ActionLink("back to employee directory", "Index")</li>
</ul>

Views/Engineers/Edit.cshtml
}

@model Factory.Models.Engineer

<h2>edit Engineer details</h2>

<hr />
<h4>@Html.DisplayFor(model => model.Name)</h4>
<br>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)
  @Html.Label("Name")
  @Html.EditorFor(model => model.Name, new { @class = "form-control"})


  @Html.Label("Assigned Machine")
  @Html.DropDownList("MachineId")

  <br>
  <br>
  <input type="submit" value="Save Changes" required="true" />
}

<ul class="menu-links">
  <li>@Html.ActionLink("back to employee directory", "Index")</li>
</ul>

Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;

<h1>Engineers</h1>

<hr />

@if (@Model.Count == 0)
{
  <h3>no engineers have been hired yet</h3>
}

<ul>
  @foreach(Engineer engineer in Model)
  {
    <li>@Html.ActionLink($"{engineer.Name}", "Details", new {id = engineer.EngineerId })</li>
  }
</ul>

<ul class="menu-links">
  <li>@Html.ActionLink("add a new engineer", "Create")</li>
  <li>@Html.ActionLink("back to home", "Index", "Home")</li>
</ul>